server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
spring:
  application:
    name: hystrix-app

# eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:7070/eureka/